### ISSUE TITLE
Remove net471 target and exclusively target .net core

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#1600]
Requires all remaining net core bugs be fixed:
- [ ] #1598 (not strictly net core specific, but will be good to get fixed)
- [x] #1540 (linux bass issue, involves dropping 32 bit target on linux)
- [x] #1592 (fix `Process.Start` regressions)

Also:

- [x] Testing of deployment
- [x] Testing of CI (unit tests etc.)
