### ISSUE TITLE
Options meta issue

### ISSUE THREAD

**Issue by SirCmpwn** [ppy/osu-framework#260]
* [x] Loading/configuration
  * [x] Defaults
  * [ ] Dependent options - WIP
* [ ] UI - WIP
  * [x] Options sections
  * [ ] Jump to section sidebar
    * [ ] And its animation
* [ ] UI wired up to bindables
* [ ] Deal with overlay clicky issues on desktop
* [ ] Rework options a bit for osu!next (some categories could be reworked)

**Comment by SirCmpwn** [comment]
See https://github.com/ppy/osu/issues/127
