### ISSUE TITLE
Add Veldrid renderer support (aka "compatibility mode")

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#4909]
We don't yet have good backwards compatibility support for older hardware, where the hardware (or drivers) don't support the OpenGL standards we rely on.

This covers adding the same level of compatibility that we have in osu-stable. It should preferably be an automatic fallback whenever opengl fails to initialise. 

---

Support progress:

- [x] Bare-minimum `IRenderer` implementation (https://github.com/ppy/osu-framework/pull/5483)
- [x] Vertex buffers support (https://github.com/ppy/osu-framework/pull/5595)
- [ ] Shaders support (https://github.com/ppy/osu-framework/pull/5647)
- [ ] Textures support (https://github.com/ppy/osu-framework/pull/5647)
- [ ] Framebuffers support (https://github.com/ppy/osu-framework/pull/5647)
- [ ] Video textures support (https://github.com/ppy/osu-framework/pull/5647)
- [ ] Handle backend-specific differences (https://github.com/ppy/osu-framework/pull/5647)
- [ ] Screenshot rendering support (https://github.com/ppy/osu-framework/commit/8ad7ed6761943519501e8179edbc8f68d4d6c1bb, wip, doesn't fully work)
- [ ] Clean-up remaining GL calls (e.g. translation functions in `BlendingParameters`)

**Comment by huupoke12** [comment]
I doubt if this is even practical to do anymore, since those hardware probably can't even run Windows 8.1 (no driver support). And .NET 6 only supports Windows 7 ESU, which probably only be purchased in enterprise environments.

**Comment by smoogipoo** [comment]
We won't be using ANGLE. We'll be using Veldrid and have native D3D/Vulkan support.

**Comment by peppy** [comment]
Also to keep in mind is that this isn't about "hardware older than Windows 8.1", but hardware/drivers which support D3D better than OpenGL.

**Comment by smoogipoo** [comment]
Closing in favour of https://github.com/ppy/osu/issues/18892
