### ISSUE TITLE
iOS performance investigations

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu-framework#5890]
iOS performance is quite bad on o!f right now, even with Metal being utilised for rendering. Initially, we've expected that decreasing the rendering resolution (i.e. using a ["render scale"](https://github.com/ppy/osu-framework/commit/18cc79542aa0363c37a932ea801c9e6f1b157cf5)) would improve performance to a usable level, but it turns out that *actually* had little to no effect.

To explain briefly, there are two phases during the rendering of a frame:
 1. The encoding phase, which represents all the time spent by the CPU queuing up (i.e. encoding) Metal commands to the command buffers.
 2. The drawing phase, which represents all the time spent by the GPU executing the submitted command buffers (processing commands, running vertex/fragment shaders).

It has been expected that iOS was behaving badly due to our draw calls and vertex/fragment shaders being unnecessarily complicated for the GPU to handle (or basically a lot of fragments to process), but actually most of the overhead is coming from the encoding phase instead.

For example, on osu! master, profiling iOS performance on song select yields 30ms-40ms being spent on encoding and 10ms being spent on drawing. Both are pretty wild intervals for such a 2D scene.

Using the "render scale" changes and downscaling the game all the way down to 0.1x decreases drawing/GPU time down to 1-2ms as expected, but the encoding time doesn't change even a notch, therefore *nothing* will feel any different in song select with render scale, it remains performing at 24-30 FPS.

## High level investigations

I've started things off by investigating this briefly at a higher level using framework test scenes which uses basic rendering functionality and monitor the frame statistics display.

I didn't gain much knowledge other than that increasing the number of masked containers rendered per frame, and/or increasing the number of native textures used on sprites, would all increase encoding time, and that's nothing new as it all indicates vertex batches being flushed quite frequently, and there are so many draw calls in the frame.

I've also noticed that the visual test browser is already adding overhead even on a blank test scene due to all the sprite texts displayed around it (test labels, control labels, etc.).

Therefore I've switched to our "sample game" project and I've made it render 500 boxes using a fill flow container with a flush between each box, and I realised the FPS counter actually went down to 40 FPS...which leads us to the next topic that I've spent around a week on...

## Low level investigations

Taking things at a lower level, with no render scaling involved, I've set up a drawable with a custom draw node that draws 500 quads with a flush after each draw (i.e. 500 draw calls), and the results were quite interesting:

![CleanShot 2023-07-04 at 18 20 25](https://github.com/ppy/osu-framework/assets/22781491/7d883925-bb79-4ea5-9019-ae44e3ffffdc)
![CleanShot 2023-07-04 at 18 21 58](https://github.com/ppy/osu-framework/assets/22781491/bae7168c-cbf9-4622-9790-1c42c1e418d5)

"Commmand Buffer 0" and "Render Command 0" represent the command buffer and rendering pass in which the 500 quads were drawn at. The GPU spent ~1ms processing these draw calls, which is mostly sane, but, the CPU has spent over 10ms encoding just that!

My immediate thoughts were that 500 draw calls are expensive to encode, but after writing a [quick Metal app with Swift](https://github.com/frenzibyte/metal-draw-test) which does the same to a certain extent, the encoding overhead in release configuration could go as low as 0.3ms!!

![CleanShot 2023-07-04 at 19 06 41](https://github.com/ppy/osu-framework/assets/22781491/dcf6fc42-5507-407d-b948-8690d3505387)
![CleanShot 2023-07-04 at 19 07 26](https://github.com/ppy/osu-framework/assets/22781491/28ed553a-4ee7-47c2-9a5a-b5bfb9307b3e)

Then I thought maybe Veldrid's implementation of Metal isn't quite optimal for iOS consumption, and I went ahead and made a quick isolated Veldrid app that pretty much copies what the Swift app above does, and the encoding overhead is oddly unstable, it could range between ~2-3ms all up to ~5ms:

![CleanShot 2023-07-04 at 19 27 11](https://github.com/ppy/osu-framework/assets/22781491/5d7af6d6-6a14-4dd2-8c63-01c9e84c993f)
![CleanShot 2023-07-04 at 19 27 26](https://github.com/ppy/osu-framework/assets/22781491/8fab7719-7ee4-4ac4-ab86-d34db1ace3c0)

~~After multiple days of investigating this, turns out our renderer implementation is being slightly inefficient (plus Veldrid validation code):~~
 - ~~Veldrid renderer fetches pipeline & resource sets from dictionaries every single draw call~~
     - ~~adds around 1ms CPU overhead per frame, therefore increasing encoding time~~
 - ~~Veldrid renderer switches to a new vertex buffer every single draw call rather than re-using the previous one until it's filled~~
     - ~~adds around 2ms encoding time overhead per frame, because `setVertexBuffer` is being called on every draw call.~~
 - ~~Veldrid's validation code being executed even in release configuration~~
     - ~~adds around 1ms CPU overhead per frame.~~

EDIT: All of the above, except for #5892 maybe, were caused by running the game under Mono interpretation. Switching to AOT as tracked in #5902 resolves the issue.

---

In summary, we're spending a lot of time encoding frames, and there's still a lot to investigate at a high level scale, the overhead may be coming from us issuing too many draw calls, or us spending too much time in draw nodes, or Veldrid not performing efficiently on iOS in certain scenarios.

The following is a list of observations I've gathered during my investigations the past week.

```[tasklist]
### Tasks
- [ ] https://github.com/ppy/osu-framework/issues/5892
- [ ] https://github.com/ppy/osu-framework/issues/5895
- [ ] https://github.com/ppy/osu-framework/issues/5920
- [ ] https://github.com/ppy/osu-framework/issues/5902
- [x] Metal rendering may get stuck waiting for next drawable every frame on iOS, potentially increasing encoding time (alleviated by waiting for drawable in `WaitForNextFrameReady`, see: https://github.com/ppy/veldrid/pull/28)
- [ ] Remove Metal command buffer completion handler for iOS Metal debugging ease
- [ ] Investigate garbage collection happening every frame on iOS
```

**Comment by frenzibyte** [comment]
I'm going to close this as iOS performance is much tolerable now compared to how it was before, the last two tasks are not as mandatory as the others to keep this issue thread open.
